### ISSUE TITLE
Map -> Add location gives mostly blank page

### ISSUE THREAD

**Issue by sjwk** [dox/energy#16]
The map page is working, but 'add location' just gives a blank page with just the header bar.  Looking at page source shows nothing inside the body tag except the header structure.
The map part of 'add node' works, but clicking only adds a marker to the map, it doesn't do anything to the mandatory location field (if it was supposed to?)

**Comment by dox** [comment]
Sorry - I missed a semi colon!  All fixed now.  Thanks for pointing out.
