### ISSUE TITLE
No interpolation

### ISSUE THREAD

**Issue by scat0324** [dox/energy#20]
Our administrator has been asked by management to provide a monthly report showing the usage compared to the same month in the previous year. However, for October 2021 the readings were taken a few days late in early November 2021 so there are no readings for that month. It seems in this case the reported usage for that month is zero!

Can anything be done to interpolate the results and give usage evened out across the requested reporting period?

**Comment by dox** [comment]
The easiest thing to do is to simply remove the reading that's a couple of days late and re-add it for the last day of the previous month - then there's a reading for each.

Interpolation would be lovely - so would the time to be able to write the code for it! 🤣

**Comment by scat0324** [comment]
Of course! Thanks @dox
