### ISSUE TITLE
Missing config

### ISSUE THREAD

**Issue by sjwk** [dox/energy#4]
Could you put a template config.php in, to show what variables should be defined?

**Comment by scat0324** [comment]
#a429e75f61be51e339e1f42733eeb25d17ff8f9e is this, I think

**Comment by scat0324** [comment]
Andrew's fixed this in #a429e75f61be51e339e1f42733eeb25d17ff8f9e

**Comment by dox** [comment]
Sorry about that! config.sample.php now included
Fixed in a429e75f61be51e339e1f42733eeb25d17ff8f9e
