### ISSUE TITLE
overlay previous year on graph

### ISSUE THREAD

**Issue by scat0324** [dox/energy#9]
Please can the CO₂ graph show a second (perhaps thinner/dotted) line with the previous year's readings, for comparison?

**Comment by dox** [comment]
This is a quick stab at it @scat0324 .  Please do let me know if it's not working for you!

**Comment by scat0324** [comment]
Thanks @dox but it doesn't quite seem to be working on our site, only the one curve has any line at all, and its colour doesn't match either in the graph legend: 
![image](https://user-images.githubusercontent.com/1536211/150567268-9605f0a0-ef42-49be-8704-37929dea226d.png)

**Comment by dox** [comment]
Hmm... I think it's because your data doesn't go that far back (it calculates a year's usage based on the previous year).  So as you don't have many readings for 2020, 2021 looks a little off.

**Comment by dox** [comment]
Actually, yes - this is exactly it.  There are only a small number of readings (mostly in October) for 2020 - so it would need more readings to provide better granularity.

![Screenshot 2022-01-24 at 12 49 06](https://user-images.githubusercontent.com/95809/150785748-fabb3986-a1dd-4ae3-a2ac-7a8f0d04409f.png)

As for the colours in the legend - quite right.  I'll get that changed.  You can tell I'm not an artist!

**Comment by scat0324** [comment]
Thanks! I'm trying to get hold of older readings from past bills. If you can sort the colours out. that would be great.
